use crossterm::event::{KeyCode, KeyModifiers};
use ratatui::Terminal;
use ratatui::backend::TestBackend;
use ratatui::layout::Rect;
use ratatui::style::{Color, Style};
use ratatui::text::{Line, Span};

use super::fixtures;
use super::harness::TuiTestHarness;
use super::scenario::TuiScenario;
use crate::quorp::tui::TuiEvent;
use crate::quorp::tui::app::{Overlay, Pane};
use crate::quorp::tui::bridge::TerminalFrame;
use crate::quorp::tui::buffer_png::{CellRasterConfig, render_frame_artifact};
use crate::quorp::tui::chat::{ChatMessage, ChatUiEvent};
use crate::quorp::tui::editor_pane::BufferSnapshot;
use crate::quorp::tui::file_tree::{DirectoryListing, TreeChild};
use crate::quorp::tui::rail_event::{
    AgentPhase, PlanStep, PlanStepStatus, RailEvent, RiskSeverity, ToolKind,
};
use crate::quorp::tui::shell::{ShellRenderer, ShellScenario, ShellState};
use crate::quorp::tui::terminal_surface::TerminalSnapshot;
use crate::quorp::tui::theme::Theme;

struct ScreenshotScenario {
    name: &'static str,
    note: &'static str,
}

fn write_bundle_manifest(scenarios: &[ScreenshotScenario]) -> std::path::PathBuf {
    let output_dir = TuiTestHarness::screenshot_output_dir();
    std::fs::create_dir_all(&output_dir).expect("mkdir screenshot output dir");
    let mut markdown = String::from("# Quorp TUI Screenshot Bundle\n\n");
    markdown.push_str("Generated by `cargo test -p quorp screenshot_suite::export_review_bundle -- --nocapture`.\n\n");
    markdown.push_str("| Scenario | File | Notes |\n");
    markdown.push_str("| --- | --- | --- |\n");
    for scenario in scenarios {
        markdown.push_str(&format!(
            "| {} | `{}` | {} |\n",
            scenario.name,
            format_args!("{}.png", scenario.name),
            scenario.note
        ));
    }
    let manifest_path = output_dir.join("INDEX.md");
    std::fs::write(&manifest_path, markdown).expect("write screenshot manifest");
    manifest_path
}

fn save_shell_screenshot(
    base_name: &str,
    cols: u16,
    rows: u16,
    scenario: ShellScenario,
) -> std::path::PathBuf {
    let area = Rect::new(0, 0, cols, rows);
    let state = ShellState::for_scenario(scenario, area);
    let backend = TestBackend::new(cols, rows);
    let mut terminal = Terminal::new(backend).expect("shell terminal");
    let theme = Theme::core_tui();
    terminal
        .draw(|frame| {
            ShellRenderer::render(frame.buffer_mut(), area, &state, &theme);
        })
        .expect("draw shell");

    let artifact = render_frame_artifact(terminal.backend().buffer(), CellRasterConfig::default());
    let output_dir = TuiTestHarness::screenshot_output_dir();
    std::fs::create_dir_all(&output_dir).expect("mkdir shell screenshot output dir");
    let png_path = output_dir.join(format!("{base_name}.png"));
    artifact.png.save(&png_path).expect("save shell screenshot");
    let dump_path = output_dir.join(format!("{base_name}.txt"));
    std::fs::write(&dump_path, artifact.plain_text_dump).expect("save shell text dump");
    png_path
}

fn seed_shell_first_command_center(scenario: TuiScenario<'_>) -> TuiScenario<'_> {
    scenario
        .rail_event(RailEvent::PhaseChanged(AgentPhase::Editing))
        .rail_event(RailEvent::OneSecondStory {
            summary:
                "Patching planner ownership resolution, then proving it with focused Rust tests before widening scope."
                    .to_string(),
        })
        .rail_event(RailEvent::TopDoubtUpdated {
            doubt: "Planner ownership may still widen public surface.".to_string(),
        })
        .rail_event(RailEvent::TimeToProofUpdated {
            eta_seconds: Some(95),
            confidence_target: Some(0.84),
        })
        .rail_event(RailEvent::ConfidenceUpdate {
            understanding: 0.86,
            merge_safety: 0.71,
            delta: 0.05,
        })
        .rail_event(RailEvent::PlanLocked {
            steps: vec![
                PlanStep {
                    label: "ground the contract".to_string(),
                    status: PlanStepStatus::Completed,
                },
                PlanStep {
                    label: "patch the narrow diff".to_string(),
                    status: PlanStepStatus::Active,
                },
                PlanStep {
                    label: "prove with targeted tests".to_string(),
                    status: PlanStepStatus::Pending,
                },
            ],
        })
        .rail_event(RailEvent::ToolStarted {
            tool_id: 12,
            name: "rg".to_string(),
            kind: ToolKind::Search,
            target: "planner ownership".to_string(),
            cwd: Some("/Users/bentaylor/Code/quorp".to_string()),
            expected_outcome: "ground the affected call sites".to_string(),
            validation_kind: None,
        })
        .rail_event(RailEvent::ToolStarted {
            tool_id: 14,
            name: "cargo_test".to_string(),
            kind: ToolKind::Test,
            target: "planner focused".to_string(),
            cwd: Some("/Users/bentaylor/Code/quorp".to_string()),
            expected_outcome: "focused proof turns green".to_string(),
            validation_kind: Some("cargo-test".to_string()),
        })
        .rail_event(RailEvent::ProofProgress {
            tests_passed: 6,
            tests_total: 9,
            coverage_delta: 0.03,
        })
        .rail_event(RailEvent::ToolCompleted {
            tool_id: 12,
            exit_code: Some(0),
            duration_ms: 420,
            files_changed: 0,
            confidence_delta: Some(0.02),
        })
        .rail_event(RailEvent::ToolCompleted {
            tool_id: 14,
            exit_code: Some(0),
            duration_ms: 1_820,
            files_changed: 1,
            confidence_delta: Some(0.05),
        })
        .rail_event(RailEvent::WatchpointAdded {
            label: "auth untouched".to_string(),
        })
        .rail_event(RailEvent::WatchpointTriggered {
            label: "auth untouched".to_string(),
            detail: "auth_guard.rs entered the candidate change radius".to_string(),
        })
        .rail_event(RailEvent::ReasoningStep {
            objective: "Narrow planner ownership resolution.".to_string(),
            evidence: vec!["Planner call sites all route through one helper.".to_string()],
            action: "Patch the helper before widening scope.".to_string(),
            expected_result: "Focused tests should prove the ownership change.".to_string(),
            rollback: Some("git checkout -- planner helper".to_string()),
            rejected_branch: Some("Skip proof and widen edit immediately.".to_string()),
        })
        .rail_event(RailEvent::SessionCheckpoint {
            label: "pre-proof".to_string(),
            commit_hash: Some("abc1234".to_string()),
        })
        .rail_event(RailEvent::ArtifactReady {
            label: "result_dir".to_string(),
            path: "/full-auto/demo-run".to_string(),
        })
        .rail_event(RailEvent::RollbackReadinessChanged {
            ready: true,
            summary: "checkpoint and diff recipe recorded".to_string(),
        })
        .rail_event(RailEvent::StopReasonSet {
            reason: "watching".to_string(),
        })
}

fn preview_fixture_harness() -> (tempfile::TempDir, TuiTestHarness) {
    let dir = fixtures::temp_project_with_files(&[
        (
            "crates/quorp/src/quorp/planner.rs",
            "pub fn plan_route() {\n    let narrowed = true;\n}\n",
        ),
        (
            "crates/quorp/src/quorp/auth_guard.rs",
            "pub fn auth_guard() {\n    let tripped = true;\n}\n",
        ),
        ("artifacts/run.log", "proof ready\n"),
    ]);
    let harness = TuiTestHarness::new_with_root(180, 50, dir.path().to_path_buf());
    (dir, harness)
}

fn open_preview_file(harness: &mut TuiTestHarness, relative_path: &str) {
    let path = harness.app.file_tree.root().join(relative_path);
    harness.app.file_tree.set_selected_file(Some(path.clone()));
    harness
        .app
        .editor_pane
        .open_preview_target(path.as_path(), harness.app.file_tree.root());
    harness
        .app
        .editor_pane
        .ensure_active_loaded(harness.app.file_tree.root());
    harness.app.focused = Pane::EditorPane;
}

#[test]
fn export_review_bundle() {
    let mut scenarios = Vec::new();

    let startup_pending_path = save_shell_screenshot(
        "startup_ready_pending_120x40",
        120,
        40,
        ShellScenario::Startup,
    );
    assert!(
        startup_pending_path.exists(),
        "missing screenshot {:?}",
        startup_pending_path
    );
    scenarios.push(ScreenshotScenario {
        name: "startup_ready_pending_120x40",
        note: "Bootstrap screen with the large animated QUORP loader before runtime readiness.",
    });

    let startup_starting_path = save_shell_screenshot(
        "startup_starting_160x50",
        160,
        50,
        ShellScenario::RuntimeStarting,
    );
    assert!(
        startup_starting_path.exists(),
        "missing screenshot {:?}",
        startup_starting_path
    );
    scenarios.push(ScreenshotScenario {
        name: "startup_starting_160x50",
        note: "Fullscreen bootstrap layout while SSD-MOE attach-or-spawn is in progress.",
    });

    let startup_failed_path = save_shell_screenshot(
        "startup_failed_server_exit_120x40",
        120,
        40,
        ShellScenario::RuntimeFailed,
    );
    assert!(
        startup_failed_path.exists(),
        "missing screenshot {:?}",
        startup_failed_path
    );
    scenarios.push(ScreenshotScenario {
        name: "startup_failed_server_exit_120x40",
        note: "Bootstrap failure state with the startup-blocking SSD-MOE error visible before chat.",
    });

    let mut default_workspace = TuiTestHarness::new(120, 40);
    default_workspace.draw();
    let default_path = default_workspace.save_screenshot("startup_default_workspace");
    assert!(
        default_path.exists(),
        "missing screenshot {:?}",
        default_path
    );
    scenarios.push(ScreenshotScenario {
        name: "startup_default_workspace",
        note: "Default launch state with the full workspace chrome visible.",
    });

    let mut proof_rail_harness = TuiTestHarness::new(180, 50);
    let proof_rail_artifacts = TuiScenario::new(
        &mut proof_rail_harness,
        "proof_rail_bundle_preview",
    )
    .rail_event(RailEvent::PhaseChanged(AgentPhase::Planning))
    .rail_event(RailEvent::OneSecondStory {
        summary: "Lock the plan, prove the narrow change, then widen only if the evidence says so."
            .to_string(),
    })
    .rail_event(RailEvent::ConfidenceUpdate {
        understanding: 0.89,
        merge_safety: 0.77,
        delta: 0.06,
    })
    .rail_event(RailEvent::PlanLocked {
        steps: vec![
            PlanStep {
                label: "ground the contract".to_string(),
                status: PlanStepStatus::Completed,
            },
            PlanStep {
                label: "run the focused proof".to_string(),
                status: PlanStepStatus::Active,
            },
            PlanStep {
                label: "only expand after proof".to_string(),
                status: PlanStepStatus::Pending,
            },
        ],
    })
    .rail_event(RailEvent::ToolStarted {
        tool_id: 44,
        name: "cargo_test".to_string(),
        kind: ToolKind::Test,
        target: "quorp".to_string(),
        cwd: None,
        expected_outcome: "focused tests pass".to_string(),
        validation_kind: Some("cargo-test".to_string()),
    })
    .rail_event(RailEvent::ToolStarted {
        tool_id: 45,
        name: "git_status".to_string(),
        kind: ToolKind::Git,
        target: ".".to_string(),
        cwd: None,
        expected_outcome: "workspace diff captured".to_string(),
        validation_kind: None,
    })
    .rail_event(RailEvent::RiskPromoted {
        description: "public API widened".to_string(),
        severity: RiskSeverity::Medium,
        blast_radius: 2,
    })
    .rail_event(RailEvent::ProofProgress {
        tests_passed: 14,
        tests_total: 18,
        coverage_delta: 0.04,
    })
    .draw()
    .save_screenshot("proof_rail_bundle_preview_180x50")
    .finish();
    let proof_rail_path = proof_rail_artifacts.screenshot_path;
    assert!(
        proof_rail_path.as_ref().is_some_and(|path| path.exists()),
        "missing proof rail screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "proof_rail_bundle_preview_180x50",
        note: "Live proof rail bundle with mission story, confidence, plan, risk, and waiting state.",
    });

    let mut rail_boot = TuiTestHarness::new(180, 50);
    rail_boot.app.force_bootstrap_for_test();
    rail_boot.draw();
    rail_boot.app.complete_bootstrap_for_test();
    let rail_boot_path = rail_boot.save_screenshot("rail_boot_transition");
    assert!(
        rail_boot_path.exists(),
        "missing screenshot {:?}",
        rail_boot_path
    );
    scenarios.push(ScreenshotScenario {
        name: "rail_boot_transition",
        note: "Bootstrap begins in the future proof rail and transitions in-place into the command center.",
    });

    let (_command_center_dir, mut command_center) = preview_fixture_harness();
    open_preview_file(&mut command_center, "crates/quorp/src/quorp/planner.rs");
    command_center
        .app
        .proof_rail
        .set_user_mode(crate::quorp::tui::proof_rail::RailMode::ControlTower);
    let command_center_artifacts = seed_shell_first_command_center(TuiScenario::new(
        &mut command_center,
        "command_center_bundle_preview",
    ))
    .rail_event(RailEvent::BlastRadiusUpdate {
        files_touched: vec![
            "crates/quorp/src/quorp/planner.rs".to_string(),
            "crates/quorp/src/quorp/auth_guard.rs".to_string(),
        ],
        symbols_changed: 4,
        net_lines_delta: 28,
    })
    .draw()
    .save_screenshot("command_center_active")
    .finish();
    assert!(
        command_center_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing command center screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "command_center_active",
        note: "Shell-first command center with one-second story, top doubt, proof ETA, watchpoints, and artifacts.",
    });

    let (_diff_lens_dir, mut diff_lens) = preview_fixture_harness();
    open_preview_file(&mut diff_lens, "crates/quorp/src/quorp/planner.rs");
    let diff_lens_artifacts = seed_shell_first_command_center(TuiScenario::new(
        &mut diff_lens,
        "diff_lens_bundle_preview",
    ))
    .rail_event(RailEvent::BlastRadiusUpdate {
        files_touched: vec![
            "crates/quorp/src/quorp/planner.rs".to_string(),
            "crates/quorp/src/quorp/auth_guard.rs".to_string(),
        ],
        symbols_changed: 4,
        net_lines_delta: 28,
    })
    .key_press(KeyCode::Char('d'), KeyModifiers::NONE)
    .draw()
    .save_screenshot("diff_lens_active")
    .finish();
    assert!(
        diff_lens_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing diff lens screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "diff_lens_active",
        note: "Diff Lens foregrounds blast radius and rollback while keeping the stream terminal-native.",
    });

    let (_verify_dir, mut verify_radar) = preview_fixture_harness();
    open_preview_file(&mut verify_radar, "crates/quorp/src/quorp/planner.rs");
    let verify_radar_artifacts = seed_shell_first_command_center(TuiScenario::new(
        &mut verify_radar,
        "verify_radar_bundle_preview",
    ))
    .key_press(KeyCode::Char('v'), KeyModifiers::NONE)
    .draw()
    .save_screenshot("verify_radar_active")
    .finish();
    assert!(
        verify_radar_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing verify radar screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "verify_radar_active",
        note: "Verify Radar pins proof progress and time-to-proof for autonomous watch mode.",
    });

    let (_terminal_jump_dir, mut terminal_jump) = preview_fixture_harness();
    terminal_jump.apply_backend_event(TuiEvent::TerminalFrame(TerminalFrame {
        snapshot: TerminalSnapshot::from_lines(&[Line::from(
            "rerun crates/quorp/src/quorp/auth_guard.rs:1 after the next patch",
        )]),
        cwd: Some(terminal_jump.app.file_tree.root().to_path_buf()),
        shell_label: Some("Terminal".to_string()),
        window_title: Some("engage-preview".to_string()),
    }));
    let terminal_jump_artifacts = TuiScenario::new(&mut terminal_jump, "terminal_path_bundle")
        .draw()
        .key_press(KeyCode::Down, KeyModifiers::ALT)
        .key_press(KeyCode::Enter, KeyModifiers::ALT)
        .draw()
        .save_screenshot("terminal_path_jump")
        .finish();
    assert!(
        terminal_jump_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing terminal path screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "terminal_path_jump",
        note: "Terminal output paths jump straight into the center preview without leaving Quorp.",
    });

    let (_artifact_dir, mut artifact_jump) = preview_fixture_harness();
    let artifact_jump_artifacts = TuiScenario::new(&mut artifact_jump, "artifact_jump_bundle")
        .rail_event(RailEvent::ArtifactReady {
            label: "run log".to_string(),
            path: "artifacts/run.log".to_string(),
        })
        .draw()
        .key_press(KeyCode::Down, KeyModifiers::ALT)
        .key_press(KeyCode::Enter, KeyModifiers::ALT)
        .draw()
        .save_screenshot("artifact_jump")
        .finish();
    assert!(
        artifact_jump_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing artifact jump screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "artifact_jump",
        note: "Artifacts open inside the center surface first, with external open left as an escape hatch.",
    });

    let (_follow_dir, mut follow_tool) = preview_fixture_harness();
    let follow_tool_artifacts = TuiScenario::new(&mut follow_tool, "follow_tool_bundle")
        .rail_event(RailEvent::ToolStarted {
            tool_id: 33,
            name: "read_file".to_string(),
            kind: ToolKind::Read,
            target: "crates/quorp/src/quorp/planner.rs".to_string(),
            cwd: None,
            expected_outcome: "review the planner helper in place".to_string(),
            validation_kind: None,
        })
        .draw()
        .key_press(KeyCode::Char('k'), KeyModifiers::CONTROL)
        .key_press(KeyCode::Char('f'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('o'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('l'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('l'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('o'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('w'), KeyModifiers::NONE)
        .key_press(KeyCode::Char(' '), KeyModifiers::NONE)
        .key_press(KeyCode::Char('t'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('o'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('o'), KeyModifiers::NONE)
        .key_press(KeyCode::Char('l'), KeyModifiers::NONE)
        .key_press(KeyCode::Enter, KeyModifiers::NONE)
        .draw()
        .save_screenshot("follow_tool_focus")
        .finish();
    assert!(
        follow_tool_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing follow tool screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "follow_tool_focus",
        note: "The control deck can follow the active tool target directly into code review in the center surface.",
    });

    let mut trace_lens = TuiTestHarness::new(180, 50);
    let trace_lens_artifacts = seed_shell_first_command_center(TuiScenario::new(
        &mut trace_lens,
        "trace_lens_bundle_preview",
    ))
    .key_press(KeyCode::Char('r'), KeyModifiers::NONE)
    .draw()
    .save_screenshot("trace_lens_active")
    .finish();
    assert!(
        trace_lens_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing trace lens screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "trace_lens_active",
        note: "Trace Lens surfaces audited reasoning artifacts instead of raw hidden thought.",
    });

    let mut timeline = TuiTestHarness::new(180, 50);
    let timeline_artifacts =
        seed_shell_first_command_center(TuiScenario::new(&mut timeline, "timeline_bundle_preview"))
            .key_press(KeyCode::Char('t'), KeyModifiers::NONE)
            .draw()
            .save_screenshot("timeline_scrubber_active")
            .finish();
    assert!(
        timeline_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing timeline screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "timeline_scrubber_active",
        note: "Timeline Scrubber shows checkpoints, stop reason, and replay affordances in the right rail.",
    });

    let benchmark_watch_root = fixtures::temp_project_with_files(&[("START_HERE.md", "# Root\n")]);
    let case_root = benchmark_watch_root.path().join("case-a");
    std::fs::create_dir_all(case_root.join("workspace").join("proof-full"))
        .expect("mkdir benchmark watch workspace");
    std::fs::write(
        case_root.join("benchmark.json"),
        serde_json::json!({
            "id": "case-a",
            "title": "Case A",
            "difficulty": "medium",
            "category": "rust",
            "repo_condition": ["proof-full"],
            "objective_file": "START_HERE.md",
            "success_file": "SUCCESS.md",
            "reset_command": "./reset.sh <condition>",
            "evaluate_command": "./evaluate.sh <condition>",
            "estimated_minutes": 5,
            "expected_files_touched": ["src/lib.rs"],
            "primary_metrics": ["tests"],
            "tags": ["watch-mode"]
        })
        .to_string(),
    )
    .expect("write benchmark manifest");
    std::fs::write(case_root.join("START_HERE.md"), "# Case\n").expect("write benchmark objective");
    std::fs::write(case_root.join("SUCCESS.md"), "done\n").expect("write success file");
    std::fs::write(case_root.join("reset.sh"), "#!/bin/sh\nexit 0\n").expect("write reset");
    std::fs::write(case_root.join("evaluate.sh"), "#!/bin/sh\nexit 0\n").expect("write evaluator");
    std::fs::write(
        case_root
            .join("workspace")
            .join("proof-full")
            .join("README.md"),
        "# Workspace\n",
    )
    .expect("write benchmark workspace");

    let mut benchmark_watch =
        TuiTestHarness::new_with_root(180, 48, benchmark_watch_root.path().to_path_buf());
    benchmark_watch.app.focused = Pane::Chat;
    benchmark_watch.app.chat.set_input_for_test(&format!(
        "/benchmark {} fix the benchmark case",
        case_root.display()
    ));
    let benchmark_watch_artifacts =
        TuiScenario::new(&mut benchmark_watch, "benchmark_watch_bundle_preview")
            .key_press(crossterm::event::KeyCode::Enter, crossterm::event::KeyModifiers::NONE)
            .rail_event(RailEvent::PhaseChanged(AgentPhase::Verifying))
            .rail_event(RailEvent::OneSecondStory {
                summary: "Patching planner ownership resolution, then proving it with focused Rust tests before widening scope.".to_string(),
            })
            .rail_event(RailEvent::WaitReason {
                explanation: "Running visible evaluator ./evaluate.sh".to_string(),
            })
            .rail_event(RailEvent::ProofProgress {
                tests_passed: 9,
                tests_total: 12,
                coverage_delta: 0.03,
            })
            .draw()
            .save_screenshot("benchmark_watch_bundle_preview_180x48")
            .finish();
    assert!(
        benchmark_watch_artifacts
            .screenshot_path
            .as_ref()
            .is_some_and(|path| path.exists()),
        "missing benchmark watch screenshot"
    );
    scenarios.push(ScreenshotScenario {
        name: "benchmark_watch_bundle_preview_180x48",
        note: "Benchmark watch mode with the proof rail focused on live proof progress and evaluator status.",
    });

    let dir = fixtures::temp_project_with_files(&[(
        "src/main.rs",
        "fn main() {\n    println!(\"hi\");\n}\n",
    )]);
    let root = dir.path().to_path_buf();
    let file_path = root.join("src/main.rs");
    let mut preview = TuiTestHarness::new_with_backend_state(120, 40, root.clone());
    preview.apply_backend_event(TuiEvent::FileTreeListed(DirectoryListing {
        parent: root.clone(),
        result: Ok(vec![TreeChild {
            path: root.join("src"),
            name: "src".to_string(),
            is_directory: true,
        }]),
    }));
    preview.app.focused = Pane::EditorPane;
    preview
        .app
        .editor_pane
        .sync_tree_selection(Some(file_path.as_path()), &root);
    preview.apply_backend_event(TuiEvent::BufferSnapshot(BufferSnapshot {
        path: Some(file_path),
        lines: vec![
            Line::from(vec![
                Span::styled("fn", Style::default().fg(Color::Magenta)),
                Span::raw(" main() {"),
            ]),
            Line::from(Span::raw("    println!(\"hi\");")),
            Line::from(Span::raw("}")),
        ],
        error: None,
        truncated: false,
    }));
    let preview_path = preview.save_screenshot("file_tree_preview");
    assert!(
        preview_path.exists(),
        "missing screenshot {:?}",
        preview_path
    );
    scenarios.push(ScreenshotScenario {
        name: "file_tree_preview",
        note: "Expanded tree with a preview buffer open in the editor pane.",
    });

    let mut terminal = TuiTestHarness::new(120, 40);
    terminal.app.focused = Pane::Terminal;
    terminal.apply_backend_event(TuiEvent::TerminalFrame(
        crate::quorp::tui::bridge::TerminalFrame {
            snapshot: crate::quorp::tui::terminal_surface::TerminalSnapshot::from_lines(&[
                Line::from("$ cargo test -p quorp"),
                Line::from(Span::styled(
                    "   Finished test profile [unoptimized + debuginfo]",
                    Style::default().fg(Color::Green),
                )),
            ]),
            cwd: Some(std::path::PathBuf::from("/Users/bentaylor/Code/quorp")),
            shell_label: Some("zsh".to_string()),
            window_title: None,
        },
    ));
    let terminal_path = terminal.save_screenshot("terminal_output");
    assert!(
        terminal_path.exists(),
        "missing screenshot {:?}",
        terminal_path
    );
    scenarios.push(ScreenshotScenario {
        name: "terminal_output",
        note: "Integrated terminal showing command output.",
    });

    let mut terminal_scrollback = TuiTestHarness::new(120, 40);
    terminal_scrollback.app.focused = Pane::Terminal;
    terminal_scrollback.apply_backend_event(TuiEvent::TerminalFrame(
        crate::quorp::tui::bridge::TerminalFrame {
            snapshot: crate::quorp::tui::terminal_surface::TerminalSnapshot::from_lines(
                &(0..18)
                    .map(|index| Line::from(format!("scrollback line {index:02}")))
                    .collect::<Vec<_>>(),
            ),
            cwd: Some(std::path::PathBuf::from("/Users/bentaylor/Code/quorp")),
            shell_label: Some("zsh".to_string()),
            window_title: None,
        },
    ));
    let terminal_scrollback_path = terminal_scrollback.save_screenshot("terminal_scrollback");
    assert!(
        terminal_scrollback_path.exists(),
        "missing screenshot {:?}",
        terminal_scrollback_path
    );
    scenarios.push(ScreenshotScenario {
        name: "terminal_scrollback",
        note: "Terminal pane with enough history to review scrollback density and spacing.",
    });

    let mut composing = TuiTestHarness::new(120, 40);
    composing.app.focused = Pane::Chat;
    composing
        .app
        .chat
        .set_input_for_test("@src/main.rs explain the startup flow");
    let composing_path = composing.save_screenshot("chat_composing");
    assert!(
        composing_path.exists(),
        "missing screenshot {:?}",
        composing_path
    );
    scenarios.push(ScreenshotScenario {
        name: "chat_composing",
        note: "Chat composer populated and ready to send.",
    });

    let mention_dir = fixtures::temp_project_with_files(&[
        ("src/main.rs", "fn main() {}\n"),
        ("src/lib.rs", "pub fn helper() {}\n"),
    ]);
    let mut mention_popup =
        TuiTestHarness::new_with_root(120, 40, mention_dir.path().to_path_buf());
    assert!(
        mention_popup.wait_path_index_ready(std::time::Duration::from_secs(8)),
        "path index should be ready for mention screenshot"
    );
    mention_popup.app.focused = Pane::Chat;
    for character in "@src/ma".chars() {
        mention_popup.key_press(KeyCode::Char(character), KeyModifiers::NONE);
    }
    mention_popup.draw();
    let mention_popup_path = mention_popup.save_screenshot("mention_popup");
    assert!(
        mention_popup_path.exists(),
        "missing screenshot {:?}",
        mention_popup_path
    );
    scenarios.push(ScreenshotScenario {
        name: "mention_popup",
        note: "Mention picker populated from the active path index.",
    });

    let mut streaming = TuiTestHarness::new(120, 40);
    streaming.app.focused = Pane::Chat;
    streaming.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Summarize the architecture".into()),
        ChatMessage::Assistant("The runtime owns".into()),
    ]);
    streaming.app.chat.set_streaming_for_test(true);
    let streaming_path = streaming.save_screenshot("chat_streaming");
    assert!(
        streaming_path.exists(),
        "missing screenshot {:?}",
        streaming_path
    );
    scenarios.push(ScreenshotScenario {
        name: "chat_streaming",
        note: "Assistant response in progress.",
    });

    let mut python_code = TuiTestHarness::new(120, 40);
    python_code.app.focused = Pane::Chat;
    python_code.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Please write this python script".into()),
        ChatMessage::Assistant("```python\nprint('hello from quorp')\n```".into()),
    ]);
    let python_code_path = python_code.save_screenshot("chat_python_code_block");
    assert!(
        python_code_path.exists(),
        "missing screenshot {:?}",
        python_code_path
    );
    scenarios.push(ScreenshotScenario {
        name: "chat_python_code_block",
        note: "Assistant Python response rendered as a boxed syntax-highlighted code block.",
    });

    let mut command_running = TuiTestHarness::new(120, 40);
    command_running.app.focused = Pane::Chat;
    command_running.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("/run cargo test -p quorp".into()),
        ChatMessage::Assistant(
            "Command request queued for confirmation.\n<run_command timeout_ms=\"30000\">cargo test -p quorp</run_command>"
                .into(),
        ),
    ]);
    command_running.app.chat.apply_chat_event(
        ChatUiEvent::StreamFinished(0),
        &command_running.app.theme.clone(),
    );
    command_running.app.chat.set_running_command_for_test(true);
    command_running.app.chat.apply_chat_event(
        ChatUiEvent::CommandOutput(0, "running tests...\n".into()),
        &command_running.app.theme.clone(),
    );
    let command_running_path = command_running.save_screenshot("command_running");
    assert!(
        command_running_path.exists(),
        "missing screenshot {:?}",
        command_running_path
    );
    scenarios.push(ScreenshotScenario {
        name: "command_running",
        note: "Command execution in progress from the chat workflow.",
    });

    let mut command_finished = TuiTestHarness::new(120, 40);
    command_finished.app.focused = Pane::Chat;
    command_finished.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Run the tests".into()),
        ChatMessage::Assistant("Done.\n[Exit code: 0]".into()),
    ]);
    let command_finished_path = command_finished.save_screenshot("command_finished");
    assert!(
        command_finished_path.exists(),
        "missing screenshot {:?}",
        command_finished_path
    );
    scenarios.push(ScreenshotScenario {
        name: "command_finished",
        note: "Completed command result visible in the transcript.",
    });

    let mut error_state = TuiTestHarness::new(120, 40);
    error_state.app.focused = Pane::Chat;
    error_state.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Explain the last command failure".into()),
        ChatMessage::Assistant("".into()),
    ]);
    error_state.app.chat.apply_chat_event(
        ChatUiEvent::Error(0, "Failed to connect to SSD-MOE: Connection refused".into()),
        &error_state.app.theme.clone(),
    );
    let error_state_path = error_state.save_screenshot("chat_error_state");
    assert!(
        error_state_path.exists(),
        "missing screenshot {:?}",
        error_state_path
    );
    scenarios.push(ScreenshotScenario {
        name: "chat_error_state",
        note: "Chat error surfaced when the local SSD-MOE stream is unavailable.",
    });

    let dir = fixtures::temp_project_with_files(&[("missing.rs", "")]);
    let root = dir.path().to_path_buf();
    let missing_path = root.join("missing.rs");
    let mut preview_error = TuiTestHarness::new_with_backend_state(120, 40, root.clone());
    preview_error.app.focused = Pane::EditorPane;
    preview_error
        .app
        .editor_pane
        .sync_tree_selection(Some(missing_path.as_path()), &root);
    preview_error.app.editor_pane.ensure_active_loaded(&root);
    preview_error.apply_backend_event(TuiEvent::BufferSnapshot(BufferSnapshot {
        path: Some(missing_path),
        lines: Vec::new(),
        error: Some("Failed to open file in project: worktree path not found".to_string()),
        truncated: false,
    }));
    let preview_error_path = preview_error.save_screenshot("file_preview_error");
    assert!(
        preview_error_path.exists(),
        "missing screenshot {:?}",
        preview_error_path
    );
    scenarios.push(ScreenshotScenario {
        name: "file_preview_error",
        note: "Preview pane showing a user-visible file open error instead of crashing.",
    });

    let mut model_picker = TuiTestHarness::new(120, 40);
    model_picker.app.focused = Pane::Chat;
    model_picker.key_press(KeyCode::Char('m'), KeyModifiers::CONTROL);
    assert_eq!(model_picker.app.overlay, Overlay::ModelPicker);
    let model_picker_path = model_picker.save_screenshot("model_picker_overlay");
    assert!(
        model_picker_path.exists(),
        "missing screenshot {:?}",
        model_picker_path
    );
    scenarios.push(ScreenshotScenario {
        name: "model_picker_overlay",
        note: "Model picker overlay for design review.",
    });

    let mut ssd_moe_starting = TuiTestHarness::new(120, 40);
    ssd_moe_starting.app.focused = Pane::Chat;
    ssd_moe_starting
        .app
        .ssd_moe
        .set_status_for_test(crate::quorp::tui::ssd_moe_tui::ModelStatus::Starting);
    let ssd_moe_starting_path = ssd_moe_starting.save_screenshot("ssd_moe_starting");
    assert!(
        ssd_moe_starting_path.exists(),
        "missing screenshot {:?}",
        ssd_moe_starting_path
    );
    scenarios.push(ScreenshotScenario {
        name: "ssd_moe_starting",
        note: "Status chrome while the local SSD-MOE runtime is starting.",
    });

    let mut ssd_moe_failed = TuiTestHarness::new(120, 40);
    ssd_moe_failed.app.focused = Pane::Chat;
    ssd_moe_failed.app.ssd_moe.set_status_for_test(
        crate::quorp::tui::ssd_moe_tui::ModelStatus::Failed(
            "SSD-MOE server binary not found".to_string(),
        ),
    );
    let ssd_moe_failed_path = ssd_moe_failed.save_screenshot("ssd_moe_failed");
    assert!(
        ssd_moe_failed_path.exists(),
        "missing screenshot {:?}",
        ssd_moe_failed_path
    );
    scenarios.push(ScreenshotScenario {
        name: "ssd_moe_failed",
        note: "Offline SSD-MOE status with an actionable startup failure visible in the chrome.",
    });

    let mut multi_session_chat = TuiTestHarness::new(120, 40);
    multi_session_chat.app.focused = Pane::Chat;
    multi_session_chat.key_press(KeyCode::Char('t'), KeyModifiers::CONTROL);
    multi_session_chat.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Session two prompt".into()),
        ChatMessage::Assistant("Session two reply".into()),
    ]);
    multi_session_chat.key_press(KeyCode::Up, KeyModifiers::ALT);
    multi_session_chat.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Session one prompt".into()),
        ChatMessage::Assistant("Session one reply".into()),
    ]);
    multi_session_chat.key_press(KeyCode::Down, KeyModifiers::ALT);
    let multi_session_chat_path = multi_session_chat.save_screenshot("multi_session_chat");
    assert!(
        multi_session_chat_path.exists(),
        "missing screenshot {:?}",
        multi_session_chat_path
    );
    scenarios.push(ScreenshotScenario {
        name: "multi_session_chat",
        note: "Multiple chat tabs present with the active session rendered in the transcript.",
    });

    let mut live_shell_default = TuiTestHarness::new(120, 40);
    let live_shell_default_path =
        live_shell_default.save_shell_preview_screenshot("live_shell_default_workspace_120x40");
    assert!(
        live_shell_default_path.exists(),
        "missing shell preview screenshot {:?}",
        live_shell_default_path
    );
    scenarios.push(ScreenshotScenario {
        name: "live_shell_default_workspace_120x40",
        note: "Live TuiApp state rendered through the new shell presenter at 120x40.",
    });

    let mut live_shell_streaming = TuiTestHarness::new(120, 40);
    live_shell_streaming.app.focused = Pane::Chat;
    live_shell_streaming.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Explain startup flow".into()),
        ChatMessage::Assistant("Quorp boots the native runtime and then streams into chat.".into()),
    ]);
    live_shell_streaming.app.chat.set_streaming_for_test(true);
    let live_shell_streaming_path =
        live_shell_streaming.save_shell_preview_screenshot("live_shell_streaming_120x40");
    assert!(
        live_shell_streaming_path.exists(),
        "missing shell preview screenshot {:?}",
        live_shell_streaming_path
    );
    scenarios.push(ScreenshotScenario {
        name: "live_shell_streaming_120x40",
        note: "Live chat streaming state rendered through the shell presenter.",
    });

    let mut live_shell_model_picker = TuiTestHarness::new(120, 40);
    live_shell_model_picker.app.focused = Pane::Chat;
    live_shell_model_picker.key_press(KeyCode::Char('m'), KeyModifiers::CONTROL);
    let live_shell_model_picker_path =
        live_shell_model_picker.save_shell_preview_screenshot("live_shell_model_picker_120x40");
    assert!(
        live_shell_model_picker_path.exists(),
        "missing shell preview screenshot {:?}",
        live_shell_model_picker_path
    );
    scenarios.push(ScreenshotScenario {
        name: "live_shell_model_picker_120x40",
        note: "Live model picker state rendered through the shell presenter.",
    });

    for (name, cols, rows, scenario, note) in [
        (
            "shell_startup_80x24",
            80,
            24,
            ShellScenario::Startup,
            "Disconnected shell startup at 80x24 with assistant as an overlay-first surface.",
        ),
        (
            "shell_startup_100x30",
            100,
            30,
            ShellScenario::Startup,
            "Disconnected shell startup at 100x30 with optional explorer and docked assistant.",
        ),
        (
            "shell_startup_120x40",
            120,
            40,
            ShellScenario::Startup,
            "Disconnected shell startup at 120x40 with explorer, dominant main area, and docked assistant.",
        ),
        (
            "shell_startup_160x50",
            160,
            50,
            ShellScenario::Startup,
            "Disconnected shell startup at 160x50 with richer header width and capped assistant dock.",
        ),
        (
            "shell_preview_120x40",
            120,
            40,
            ShellScenario::Preview,
            "Disconnected shell preview scenario with readable code content in the main workspace.",
        ),
        (
            "shell_assistant_streaming_80x24",
            80,
            24,
            ShellScenario::AssistantStreaming,
            "Disconnected shell streaming state at 80x24 where the assistant takes overlay priority.",
        ),
        (
            "shell_assistant_streaming_120x40",
            120,
            40,
            ShellScenario::AssistantStreaming,
            "Disconnected shell streaming state at 120x40 with docked assistant transcript.",
        ),
        (
            "shell_command_running_100x30",
            100,
            30,
            ShellScenario::CommandRunning,
            "Disconnected shell command-running state with terminal output integrated into the main workspace.",
        ),
        (
            "shell_command_error_100x30",
            100,
            30,
            ShellScenario::CommandError,
            "Disconnected shell failure state keeping the error inline in assistant context.",
        ),
        (
            "shell_model_picker_120x40",
            120,
            40,
            ShellScenario::ModelPicker,
            "Disconnected shell model selector overlay with terminal-native list density.",
        ),
        (
            "shell_help_120x40",
            120,
            40,
            ShellScenario::Help,
            "Disconnected shell help overlay focused on keyboard actions rather than pane chrome.",
        ),
        (
            "shell_runtime_starting_120x40",
            120,
            40,
            ShellScenario::RuntimeStarting,
            "Disconnected shell startup state while SSD-MOE is coming online.",
        ),
        (
            "shell_runtime_failed_120x40",
            120,
            40,
            ShellScenario::RuntimeFailed,
            "Disconnected shell runtime failure state with an inline recovery message.",
        ),
    ] {
        let path = save_shell_screenshot(name, cols, rows, scenario);
        assert!(path.exists(), "missing shell screenshot {:?}", path);
        scenarios.push(ScreenshotScenario { name, note });
    }

    let manifest_path = write_bundle_manifest(&scenarios);
    assert!(
        manifest_path.exists(),
        "missing screenshot manifest {:?}",
        manifest_path
    );
}
