use crossterm::event::{KeyCode, KeyModifiers};
use ratatui::style::{Color, Style};
use ratatui::text::{Line, Span};

use super::fixtures;
use super::harness::TuiTestHarness;
use crate::quorp::tui::TuiEvent;
use crate::quorp::tui::app::{Overlay, Pane};
use crate::quorp::tui::chat::{ChatMessage, ChatUiEvent};
use crate::quorp::tui::editor_pane::BufferSnapshot;
use crate::quorp::tui::file_tree::{DirectoryListing, TreeChild};

struct ScreenshotScenario {
    name: &'static str,
    note: &'static str,
}

fn write_bundle_manifest(scenarios: &[ScreenshotScenario]) -> std::path::PathBuf {
    let output_dir = TuiTestHarness::screenshot_output_dir();
    std::fs::create_dir_all(&output_dir).expect("mkdir screenshot output dir");
    let mut markdown = String::from("# Quorp TUI Screenshot Bundle\n\n");
    markdown.push_str("Generated by `cargo test -p quorp screenshot_suite::export_review_bundle -- --nocapture`.\n\n");
    markdown.push_str("| Scenario | File | Notes |\n");
    markdown.push_str("| --- | --- | --- |\n");
    for scenario in scenarios {
        markdown.push_str(&format!(
            "| {} | `{}` | {} |\n",
            scenario.name,
            format!("{}.png", scenario.name),
            scenario.note
        ));
    }
    let manifest_path = output_dir.join("INDEX.md");
    std::fs::write(&manifest_path, markdown).expect("write screenshot manifest");
    manifest_path
}

#[test]
fn export_review_bundle() {
    let mut scenarios = Vec::new();

    let mut default_workspace = TuiTestHarness::new(120, 40);
    default_workspace.draw();
    let default_path = default_workspace.save_screenshot("startup_default_workspace");
    assert!(default_path.exists(), "missing screenshot {:?}", default_path);
    scenarios.push(ScreenshotScenario {
        name: "startup_default_workspace",
        note: "Default launch state with the full workspace chrome visible.",
    });

    let dir = fixtures::temp_project_with_files(&[("src/main.rs", "fn main() {\n    println!(\"hi\");\n}\n")]);
    let root = dir.path().to_path_buf();
    let file_path = root.join("src/main.rs");
    let mut preview = TuiTestHarness::new_with_backend_state(120, 40, root.clone());
    preview.apply_backend_event(TuiEvent::FileTreeListed(DirectoryListing {
        parent: root.clone(),
        result: Ok(vec![TreeChild {
            path: root.join("src"),
            name: "src".to_string(),
            is_directory: true,
        }]),
    }));
    preview.app.focused = Pane::EditorPane;
    preview.app.editor_pane.sync_tree_selection(Some(file_path.as_path()), &root);
    preview.apply_backend_event(TuiEvent::BufferSnapshot(BufferSnapshot {
        path: Some(file_path),
        lines: vec![
            Line::from(vec![
                Span::styled("fn", Style::default().fg(Color::Magenta)),
                Span::raw(" main() {"),
            ]),
            Line::from(Span::raw("    println!(\"hi\");")),
            Line::from(Span::raw("}")),
        ],
        error: None,
        truncated: false,
    }));
    let preview_path = preview.save_screenshot("file_tree_preview");
    assert!(preview_path.exists(), "missing screenshot {:?}", preview_path);
    scenarios.push(ScreenshotScenario {
        name: "file_tree_preview",
        note: "Expanded tree with a preview buffer open in the editor pane.",
    });

    let mut terminal = TuiTestHarness::new(120, 40);
    terminal.app.focused = Pane::Terminal;
    terminal.apply_backend_event(TuiEvent::TerminalFrame(
        crate::quorp::tui::bridge::TerminalFrame {
            lines: vec![
                Line::from("$ cargo test -p quorp"),
                Line::from(Span::styled(
                    "   Finished test profile [unoptimized + debuginfo]",
                    Style::default().fg(Color::Green),
                )),
            ],
        },
    ));
    let terminal_path = terminal.save_screenshot("terminal_output");
    assert!(terminal_path.exists(), "missing screenshot {:?}", terminal_path);
    scenarios.push(ScreenshotScenario {
        name: "terminal_output",
        note: "Integrated terminal showing command output.",
    });

    let mut composing = TuiTestHarness::new(120, 40);
    composing.app.focused = Pane::Chat;
    composing.app.chat.set_input_for_test("@src/main.rs explain the startup flow");
    let composing_path = composing.save_screenshot("chat_composing");
    assert!(composing_path.exists(), "missing screenshot {:?}", composing_path);
    scenarios.push(ScreenshotScenario {
        name: "chat_composing",
        note: "Chat composer populated and ready to send.",
    });

    let mut streaming = TuiTestHarness::new(120, 40);
    streaming.app.focused = Pane::Chat;
    streaming.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Summarize the architecture".into()),
        ChatMessage::Assistant("The runtime owns".into()),
    ]);
    streaming.app.chat.set_streaming_for_test(true);
    let streaming_path = streaming.save_screenshot("chat_streaming");
    assert!(streaming_path.exists(), "missing screenshot {:?}", streaming_path);
    scenarios.push(ScreenshotScenario {
        name: "chat_streaming",
        note: "Assistant response in progress.",
    });

    let mut command_running = TuiTestHarness::new(120, 40);
    command_running.app.focused = Pane::Chat;
    command_running.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("/run cargo test -p quorp".into()),
        ChatMessage::Assistant(
            "Command request queued for confirmation.\n<run_command timeout_ms=\"30000\">cargo test -p quorp</run_command>"
                .into(),
        ),
    ]);
    command_running.app.chat.apply_chat_event(
        ChatUiEvent::StreamFinished(0),
        &command_running.app.theme.clone(),
    );
    command_running.app.chat.set_running_command_for_test(true);
    command_running
        .app
        .chat
        .apply_chat_event(ChatUiEvent::CommandOutput(0, "running tests...\n".into()), &command_running.app.theme.clone());
    let command_running_path = command_running.save_screenshot("command_running");
    assert!(
        command_running_path.exists(),
        "missing screenshot {:?}",
        command_running_path
    );
    scenarios.push(ScreenshotScenario {
        name: "command_running",
        note: "Command execution in progress from the chat workflow.",
    });

    let mut command_finished = TuiTestHarness::new(120, 40);
    command_finished.app.focused = Pane::Chat;
    command_finished.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Run the tests".into()),
        ChatMessage::Assistant("Done.\n[Exit code: 0]".into()),
    ]);
    let command_finished_path = command_finished.save_screenshot("command_finished");
    assert!(
        command_finished_path.exists(),
        "missing screenshot {:?}",
        command_finished_path
    );
    scenarios.push(ScreenshotScenario {
        name: "command_finished",
        note: "Completed command result visible in the transcript.",
    });

    let mut error_state = TuiTestHarness::new(120, 40);
    error_state.app.focused = Pane::Chat;
    error_state.app.chat.seed_messages_for_test(vec![
        ChatMessage::User("Explain the last command failure".into()),
        ChatMessage::Assistant("".into()),
    ]);
    error_state
        .app
        .chat
        .apply_chat_event(ChatUiEvent::Error(0, "Failed to connect to SSD-MOE: Connection refused".into()), &error_state.app.theme.clone());
    let error_state_path = error_state.save_screenshot("chat_error_state");
    assert!(error_state_path.exists(), "missing screenshot {:?}", error_state_path);
    scenarios.push(ScreenshotScenario {
        name: "chat_error_state",
        note: "Chat error surfaced when the local SSD-MOE stream is unavailable.",
    });

    let mut model_picker = TuiTestHarness::new(120, 40);
    model_picker.app.focused = Pane::Chat;
    model_picker.key_press(KeyCode::Char('m'), KeyModifiers::CONTROL);
    assert_eq!(model_picker.app.overlay, Overlay::ModelPicker);
    let model_picker_path = model_picker.save_screenshot("model_picker_overlay");
    assert!(
        model_picker_path.exists(),
        "missing screenshot {:?}",
        model_picker_path
    );
    scenarios.push(ScreenshotScenario {
        name: "model_picker_overlay",
        note: "Model picker overlay for design review.",
    });

    let manifest_path = write_bundle_manifest(&scenarios);
    assert!(manifest_path.exists(), "missing screenshot manifest {:?}", manifest_path);
}
